/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-white',
    'text-white',
    'bg-black',
    'text-black',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-gray-500',
    'bg-opacity-10',
    'bg-opacity-20',
    'bg-opacity-30',
    'bg-opacity-40',
    'bg-opacity-50',
    'bg-opacity-60',
    'bg-opacity-70',
    'bg-opacity-80',
    'bg-opacity-90',
    'bg-opacity-95',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'text-gray-500',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
  ],
  theme: {
    extend: {
      colors: {
        white: "#FFFFFF",
        black: "#000000",
        gray: {
          100: "#f3f4f6",
          200: "#e5e7eb",
          300: "#d1d5db",
          400: "#9ca3af",
          500: "#6b7280",
          600: "#4b5563",
          700: "#374151",
          800: "#1f2937",
          900: "#111827",
        },
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        accent: "var(--accent-green)",
        coral: "var(--accent-coral)",
        navy: "var(--accent-black)",
        ocean: "var(--bg-ocean)",
      },
      backgroundColor: {
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        accent: "var(--accent-green)",
        white: "#FFFFFF",
        coral: "var(--accent-coral)",
        navy: "var(--accent-black)",
        ocean: "var(--bg-ocean)",
      },
      textColor: {
        primary: "var(--text-primary)",
        secondary: "var(--text-secondary)",
        light: "var(--text-light)",
        white: "#FFFFFF",
        coral: "var(--accent-coral)",
        navy: "var(--accent-black)",
      },
      animation: {
        "wave-pulse": "wave-pulse 4s ease-in-out infinite",
      },
      keyframes: {
        "wave-pulse": {
          "0%, 100%": { opacity: 0.4 },
          "50%": { opacity: 0.7 },
        },
      },
    },
  },
  plugins: [],
};
